### PR TITLE
Re-use expensive stats object

### LINKED ISSUE #92: Performance regression on Webpack 5
I noticed the plugins performs considerably worse on Webpack 5 vs. Webpack 4. A build that previously took 4 minutes took over 9 minutes and I've narrowed down the regression to this plugin. 

Some of that slowness can be attributed to Webpack 5 which in my testing shows around a 15-20% performance regression compared to Webpack 4, but there certainly seems to be something about this plugin.

### PR DESCRIPTION
**Pull request by markjm**
Hi @xz64 -  thanks for your continued work on this plugin.

The recent change which calls getStats seems to cause a large perf regression in large projects. getStats is extremely expensive in large projects. Calling it repeatedly causes a huge spike in build time. I wrapped the toJson call in a console.time and received results as below. In large projects there are both (1) a large number of chunks, meaning the toJson will be called multiple times, and (2) a slower toJson.

image

To resolve the issue, we just call toJson once and pass that instance around to inspect the results.

Fixes #92

### CODE REVIEW

File: src/WebpackChunkHandler.ts [hunk 1]
```diff
@@ -2,12 +2,14 @@ import { WebpackChunk } from './WebpackChunk';
...
 import { WebpackCompilation } from './WebpackCompilation';
+import { WebpackStats } from './WebpackStats';
 
 interface WebpackChunkHandler {
   processChunk(
     compilation: WebpackCompilation,
     chunk: WebpackChunk,
-    moduleCache: ModuleCache
+    moduleCache: ModuleCache,
+    stats: WebpackStats | undefined
```
Comment (xz64) [inline src/WebpackChunkHandler.ts:12]: In what scenario will the stats be undefined?

Comment (markjm) [reply src/WebpackChunkHandler.ts:12]: since we do not need to even make this call for WP 3 & 4, we dont. Note the getStats call in the CompilerHandler is only hit if we are using WP5 (guarded by the existance of the processAssets hook). So essentially it is present whenever it is used (WP5) and undefined when it is not (WP<5)

File: src/WebpackChunkModuleIterator.ts [hunk 2]
```diff
@@ -9,18 +9,19 @@ class WebpackChunkModuleIterator {
   iterateModules(
     compilation: WebpackCompilation,
     chunk: WebpackChunk,
+    stats: WebpackStats | undefined,
     callback: ((module: WebpackChunkModule) => void)
   ): void {
-    if (typeof compilation.chunkGraph !== 'undefined') {
+    if (
+      typeof compilation.chunkGraph !== 'undefined' &&
+      typeof stats !== 'undefined'
```
Comment (markjm) [inline src/WebpackChunkModuleIterator.ts:17]: Any one of these checks is enough to ensure we are running in WP5, but we include both mainly for type-narrowing (so typescript knows chunkGraph and stats are defined in this case)

**Comment by xz64** [comment]
LGTM. Thanks for looking into this.

**Comment by markjm** [comment]
Thanks for quick review. Is cutting a new build automatic? If not, do you need anything from me to do get a new version rolling

**Comment by xz64** [comment]
It's not automatic, but I just published this v2.3.11 which contains the fix.
